"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv
from django.utils.csp import CSP


BASE_DIR = Path(__file__).resolve().parent.parent


def env_string(
    name: str,
    default: str = "",
) -> str:
    return os.getenv(name, default).strip()


def env_bool(
    name: str,
    default: bool = False,
) -> bool:
    value = os.getenv(name)

    if value is None:
        return default

    return value.strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def env_int(
    name: str,
    default: int,
) -> int:
    value = os.getenv(name)

    if value is None:
        return default

    try:
        return int(value)

    except ValueError as exc:
        raise ValueError(
            f"Environment variable {name} must be an integer."
        ) from exc


def env_list(
    name: str,
    default: list[str] | None = None,
) -> list[str]:
    value = os.getenv(name)

    if value is None:
        return default or []

    return [
        item.strip()
        for item in value.split(",")
        if item.strip()
    ]


load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY_MATERIAL = env_string(
    "DJANGO_SECRET_KEY",
    "development-only-secret-key-change-me",
)

# Namespacing preserves the full entropy of provider-generated secrets and
# ensures Django receives a suitably long signing key. Validate the original
# material below so a known development placeholder can never pass production
# checks merely because of this prefix.
SECRET_KEY = (
    "threatlens-django-signing:"
    f"{_SECRET_KEY_MATERIAL}"
)

DEBUG = env_bool(
    "DJANGO_DEBUG",
    False,
)

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    [
        "127.0.0.1",
        "localhost",
    ],
)

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
)

# Render supplies its assigned hostname at runtime. Adding that trusted
# platform value keeps Blueprint deployments secure without hardcoding a
# service name that Render may suffix for uniqueness.
RENDER_EXTERNAL_HOSTNAME = env_string(
    "RENDER_EXTERNAL_HOSTNAME",
)

if RENDER_EXTERNAL_HOSTNAME:
    if RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(
            RENDER_EXTERNAL_HOSTNAME
        )

    render_origin = (
        f"https://{RENDER_EXTERNAL_HOSTNAME}"
    )

    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(
            render_origin
        )

OPENAI_API_KEY = env_string("OPENAI_API_KEY")
OPENAI_MODEL = env_string("OPENAI_MODEL", "gpt-5.6")
OPENAI_MAX_RETRIES = env_int("OPENAI_MAX_RETRIES", 2)

THREATLENS_MAX_INPUT_CHARACTERS = env_int(
    "THREATLENS_MAX_INPUT_CHARACTERS",
    30_000,
)

THREATLENS_ANALYSIS_TIMEOUT_SECONDS = env_int(
    "THREATLENS_ANALYSIS_TIMEOUT_SECONDS",
    90,
)

THREATLENS_DEMO_MODE = env_bool(
    "THREATLENS_DEMO_MODE",
    DEBUG,
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "analyzer",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "analyzer.middleware.RequestIDMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}

# ThreatLens security-event upload limits.
THREATLENS_MAX_UPLOAD_BYTES = env_int(
    "THREATLENS_MAX_UPLOAD_BYTES",
    5 * 1024 * 1024,
)

# Reject multipart requests containing more files than ThreatLens accepts.
# A reverse proxy must still enforce the overall request-body limit.
DATA_UPLOAD_MAX_NUMBER_FILES = 1

THREATLENS_MAX_PARSED_CHARACTERS = env_int(
    "THREATLENS_MAX_PARSED_CHARACTERS",
    200_000,
)

THREATLENS_ALLOWED_UPLOAD_EXTENSIONS = {
    ".txt",
    ".log",
    ".json",
    ".jsonl",
    ".csv",
}

LOG_LEVEL = env_string(
    "DJANGO_LOG_LEVEL",
    "INFO",
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": (
                "{asctime} {levelname} "
                "{name} request_id={request_id} "
                "{message}"
            ),
            "style": "{",
        },
        "django": {
            "format": (
                "{asctime} {levelname} "
                "{name} {message}"
            ),
            "style": "{",
        },
    },
    "filters": {
        "request_id": {
            "()": (
                "analyzer.logging_filters."
                "RequestIDLogFilter"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": [
                "request_id",
            ],
        },
        "django_console": {
            "class": "logging.StreamHandler",
            "formatter": "django",
        },
    },
    "loggers": {
        "analyzer": {
            "handlers": [
                "console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django": {
            "handlers": [
                "django_console",
            ],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Django 6's built-in CSP blocks untrusted executable content while allowing
# ThreatLens's same-origin static assets and form submissions.
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "base-uri": [CSP.SELF],
    "connect-src": [CSP.SELF],
    "font-src": [CSP.SELF],
    "form-action": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
    "img-src": [CSP.SELF],
    "object-src": [CSP.NONE],
    "script-src": [CSP.SELF],
    "style-src": [CSP.SELF],
}


if not DEBUG:
    if (
        len(_SECRET_KEY_MATERIAL) < 40
        or len(set(_SECRET_KEY_MATERIAL)) < 5
        or _SECRET_KEY_MATERIAL.startswith(
            "django-insecure-"
        )
        or "change-me" in _SECRET_KEY_MATERIAL.lower()
        or "replace-with" in _SECRET_KEY_MATERIAL.lower()
    ):
        raise RuntimeError(
            "DJANGO_SECRET_KEY must contain at least 40 characters of "
            "strong, unique production secret material."
        )

    SECURE_SSL_REDIRECT = env_bool(
        "DJANGO_SECURE_SSL_REDIRECT",
        True,
    )

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = env_int(
        "DJANGO_SECURE_HSTS_SECONDS",
        3600,
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
        False,
    )

    SECURE_HSTS_PRELOAD = env_bool(
        "DJANGO_SECURE_HSTS_PRELOAD",
        False,
    )

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = "DENY"

    SECURE_REFERRER_POLICY = (
        "strict-origin-when-cross-origin"
    )

    if env_bool(
        "DJANGO_TRUST_X_FORWARDED_PROTO",
        False,
    ):
        SECURE_PROXY_SSL_HEADER = (
            "HTTP_X_FORWARDED_PROTO",
            "https",
        )
