# Generated by Django 6.0.7 on 2026-07-18 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=20)),
                ('summary', models.TextField()),
                ('raw_events', models.TextField(help_text='Sanitized security-event data submitted for analysis.')),
                ('analysis', models.JSONField(help_text='Structured AI incident assessment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='inv_severity_created_idx'), models.Index(fields=['confidence', '-created_at'], name='inv_conf_created_idx')],
            },
        ),
    ]
