# Generated by Django 6.0.7 on 2026-07-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='input_source',
            field=models.CharField(choices=[('pasted', 'Pasted text'), ('uploaded_file', 'Uploaded file')], db_index=True, default='pasted', max_length=20),
        ),
        migrations.AddField(
            model_name='investigation',
            name='source_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investigation',
            name='source_event_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investigation',
            name='source_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
